/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteTripsRouteImport } from './routes/_site.trips'
import { Route as SiteGalleryRouteImport } from './routes/_site.gallery'
import { Route as SiteContactRouteImport } from './routes/_site.contact'
import { Route as SiteBlogRouteImport } from './routes/_site.blog'
import { Route as SiteAboutRouteImport } from './routes/_site.about'
import { Route as SiteAdventuresIndexRouteImport } from './routes/_site.adventures.index'
import { Route as SiteAdventuresSlugRouteImport } from './routes/_site.adventures.$slug'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTripsRoute = SiteTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => SiteRoute,
} as any)
const SiteGalleryRoute = SiteGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SiteBlogRoute = SiteBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAdventuresIndexRoute = SiteAdventuresIndexRouteImport.update({
  id: '/adventures/',
  path: '/adventures/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAdventuresSlugRoute = SiteAdventuresSlugRouteImport.update({
  id: '/adventures/$slug',
  path: '/adventures/$slug',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/about': typeof SiteAboutRoute
  '/blog': typeof SiteBlogRoute
  '/contact': typeof SiteContactRoute
  '/gallery': typeof SiteGalleryRoute
  '/trips': typeof SiteTripsRoute
  '/adventures/$slug': typeof SiteAdventuresSlugRoute
  '/adventures/': typeof SiteAdventuresIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof SiteAboutRoute
  '/blog': typeof SiteBlogRoute
  '/contact': typeof SiteContactRoute
  '/gallery': typeof SiteGalleryRoute
  '/trips': typeof SiteTripsRoute
  '/': typeof SiteIndexRoute
  '/adventures/$slug': typeof SiteAdventuresSlugRoute
  '/adventures': typeof SiteAdventuresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/_site/about': typeof SiteAboutRoute
  '/_site/blog': typeof SiteBlogRoute
  '/_site/contact': typeof SiteContactRoute
  '/_site/gallery': typeof SiteGalleryRoute
  '/_site/trips': typeof SiteTripsRoute
  '/_site/': typeof SiteIndexRoute
  '/_site/adventures/$slug': typeof SiteAdventuresSlugRoute
  '/_site/adventures/': typeof SiteAdventuresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/gallery'
    | '/trips'
    | '/adventures/$slug'
    | '/adventures/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/blog'
    | '/contact'
    | '/gallery'
    | '/trips'
    | '/'
    | '/adventures/$slug'
    | '/adventures'
  id:
    | '__root__'
    | '/_site'
    | '/_site/about'
    | '/_site/blog'
    | '/_site/contact'
    | '/_site/gallery'
    | '/_site/trips'
    | '/_site/'
    | '/_site/adventures/$slug'
    | '/_site/adventures/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/trips': {
      id: '/_site/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof SiteTripsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/gallery': {
      id: '/_site/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof SiteGalleryRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/blog': {
      id: '/_site/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof SiteBlogRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/adventures/': {
      id: '/_site/adventures/'
      path: '/adventures'
      fullPath: '/adventures/'
      preLoaderRoute: typeof SiteAdventuresIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/adventures/$slug': {
      id: '/_site/adventures/$slug'
      path: '/adventures/$slug'
      fullPath: '/adventures/$slug'
      preLoaderRoute: typeof SiteAdventuresSlugRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteBlogRoute: typeof SiteBlogRoute
  SiteContactRoute: typeof SiteContactRoute
  SiteGalleryRoute: typeof SiteGalleryRoute
  SiteTripsRoute: typeof SiteTripsRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteAdventuresSlugRoute: typeof SiteAdventuresSlugRoute
  SiteAdventuresIndexRoute: typeof SiteAdventuresIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteBlogRoute: SiteBlogRoute,
  SiteContactRoute: SiteContactRoute,
  SiteGalleryRoute: SiteGalleryRoute,
  SiteTripsRoute: SiteTripsRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteAdventuresSlugRoute: SiteAdventuresSlugRoute,
  SiteAdventuresIndexRoute: SiteAdventuresIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
